[2023-04-20 10:03:34,936] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:03:34] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:03:40,692] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:03:40] "[33mGET /produtos HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:06,411] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.15.25:5002 (Press CTRL+C to quit) - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:09,316] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:09] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:09,322] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:09] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:09,334] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:09] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:09,335] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:09] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:09,336] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:09] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:09,531] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:09] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:31,948] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:31] "POST /previsao HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:32,852] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:32] "POST /previsao HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:42,494] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:42] "GET /previsoes HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:43,813] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:43] "GET /previsoes HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:57,729] WARNING get_produto() L104  Erro ao buscar previsao 'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L104 
[2023-04-20 10:05:57,730] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:57] "[33mGET /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:05:58,647] WARNING get_produto() L104  Erro ao buscar previsao 'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L104 
[2023-04-20 10:05:58,649] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:05:58] "[33mGET /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:06:12,012] WARNING del_previsao() L135  Erro ao deletar previsao #'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L135 
[2023-04-20 10:06:12,013] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:06:12] "[33mDELETE /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:06:22,496] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:06:22] "[33mGET /produtos HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:06:44,543] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:06:44] "[33mPOST /produto HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:06:58,134] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:06:58] "[33mPOST /produto HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:07:02,838] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:07:02] "[33mOPTIONS /produto?nome=camburi HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:31,357] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.15.25:5002 (Press CTRL+C to quit) - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:33,287] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:09:33] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:33,293] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:09:33] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:33,309] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:09:33] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:33,310] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:09:33] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:33,312] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:09:33] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:33,485] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:09:33] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:57,810] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:09:57] "POST /previsao HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:09:59,142] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:09:59] "POST /previsao HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:10:08,252] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:10:08] "GET /previsoes HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:10:09,518] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:10:09] "GET /previsoes HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:10:22,930] WARNING get_produto() L104  Erro ao buscar previsao 'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L104 
[2023-04-20 10:10:22,934] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:10:22] "[33mGET /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:10:37,245] WARNING del_previsao() L135  Erro ao deletar previsao #'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L135 
[2023-04-20 10:10:37,246] INFO _log() L224  127.0.0.1 - - [20/Apr/2023 10:10:37] "[33mDELETE /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-20 10:10:38,150] WARNING del_previsao() L135  Erro ao deletar previsao #'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L135 
